name: CI/CD
on:
  workflow_call:
  workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: ${{ !contains(github.ref, 'main') }}
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Publish Test Version
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          docker login -u francoisjn -p $DOCKER_PASSWORD
          make publish PLUGIN_TAG=test

      - name: Run Tests
        run: |
          sudo chmod ugo+rwx /var/lib/docker 
          sudo mkdir /var/lib/docker/x-drives
          sudo chmod ugo+rwx /var/lib/docker/x-drives
          make config
          python -m unittest discover -s tests -p "*.py"

      - name: Delete Test Version
        env:
          API_TOKEN: ${{ secrets.DOCKER_HUB_API_TOKEN }}
        run: |
          make unpublish API_TOKEN=$API_TOKEN PLUGIN_TAG=test
  deploy:
    if: github.ref_name == 'master' || github.ref_name == 'main'
    name: Deploy
    needs:
      - test
    uses: ./.github/workflows/deploy.yml
    secrets: inherit