name: CI/CD
on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '.gitignore'
      - '.mergify.yml'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Publish Test Version
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          docker login -u francoisjn -p $DOCKER_PASSWORD
          make publish PLUGIN_TAG=test

      - name: Run Tests
        run: |
          sudo chmod ugo+rwx /var/lib/docker 
          sudo mkdir /var/lib/docker/x-drives
          sudo chmod ugo+rwx /var/lib/docker/x-drives
          make config
#          TODO: reenable tests
#          python -m unittest discover -s tests -p "*.py"

      - name: Delete Test Version
        env:
          API_TOKEN: ${{ secrets.DOCKER_HUB_API_TOKEN }}
        run: |
          make delete_test API_TOKEN=$API_TOKEN
  deploy:
    name: Deploy
    needs:
      - test
    uses: ./.github/workflows/deploy.yml
    secrets: inherit